### ISSUE TITLE
Not working on latest Safari

### ISSUE THREAD

**Issue by anstapol** [hotwired/stimulus-site#8]
Hey guys, just wanted you to know that the example on your homepage doesn't work on safari.
https://stimulus.hotwire.dev#hello

MacOS version 11.1
Safari version 14.0.2

**Comment by javan** [comment]
Confirmed. Seeing a JavaScript error in Safari. Works correctly in Firefox and Chrome. 

Guessing this was introduced by https://github.com/hotwired/stimulus-site/pull/7. @vampeel, maybe the `esbuild` settings / flags need tweaking?

**Comment by adamstddrd** [comment]
Generally, this is traceable to not using Babel. Specifically, Safari has buggy support for public class fields. See [this SO topic](https://stackoverflow.com/questions/60026651/safari-unexpected-token-expected-an-opening-before-a-methods-paramet) and the [related Webkit bug](https://bugs.webkit.org/show_bug.cgi?id=194095). It's fixed in Safari Tech Preview, but that obviously is not a workable solution.

@javan is there a Babel-free method of defining targets for a controller that doesn't rely on public class fields?

**Comment by adamstddrd** [comment]
Just deployed [a fix for this](https://github.com/hotwired/stimulus-site/commit/831646fff07af104defbf568b8b976077aa6fe51). The solution was to use the ["using without a build system" method](https://stimulus.hotwire.dev/handbook/installing#using-without-a-build-system). I hadn't considered using this approach as I _am_ using a build system, just not one that uses Babel to transpile.
